### ISSUE TITLE
Can this be used in Java...If so please let me know how to implement this in a web application

### ISSUE THREAD

**Issue by dine1987** [elasticfence/elasticsearch-http-user-auth#74]

**Comment by jemacom** [comment]
This is a plugin to secure Elasticseach indices. Meaning that it adds a layer of authentication on top since by default there's no restrictions to query, add and modify Elasticsearch indexes. 

In your use case, securing a web app, I don't think this is the right place to be. Novertheless you can learn from the plugin design by looking to docs and source code ;)

**Comment by lmangani** [comment]
Thanks @jemacom for summarizing the correct answer :)
